# -*- coding: utf-8 -*-
"""E-commerce Return Rate Reduction Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J8mxaWFePDNuyMG6Z9nQLaHdepHbERIQ
"""

import pandas as pd
import numpy as np

# 1. Load YOUR dataset
# 'latin1' encoding is used because the file has some special characters
orders = pd.read_csv('superstore.csv', encoding='latin1')

# 2. Extract unique Order IDs
unique_orders = orders['Order.ID'].unique()

# 3. Simulate realistic Returns data for your specific orders
np.random.seed(42) # Ensures you get the same results every time
returns_list = []
reasons = ['Defective', 'Wrong Item Shipped', 'Not as Expected', 'Arrived Damaged']

for order_id in unique_orders:
    # We will simulate roughly a 6% return rate across the store
    if np.random.rand() < 0.06:
        returns_list.append({
            'Order.ID': order_id,
            'Returned': 'Yes',
            'Return.Reason': np.random.choice(reasons)
        })

returns = pd.DataFrame(returns_list)

# 4. Save the Returns data as a new CSV
returns.to_csv('Returns.csv', index=False)

print(f"✅ Step 1 Complete!")
print(f"Loaded {len(orders)} items from your 'superstore.csv'.")
print(f"Generated a 'Returns.csv' file with {len(returns)} returned orders.")

import sqlite3

# 1. Create a local SQL database in Python
conn = sqlite3.connect('ecommerce_project.db')

# 2. Load both tables into the SQL database
orders.to_sql('Orders', conn, index=False, if_exists='replace')
returns.to_sql('Returns', conn, index=False, if_exists='replace')

# 3. Write the SQL Query to JOIN them
sql_query = """
SELECT
    o.[Order.ID],
    o.[Product.Name],
    o.Category,
    o.[Sub.Category],
    o.Region,
    o.Sales,
    o.Profit,
    -- If the order is in the Returns table, mark as 1, else 0
    CASE WHEN r.Returned = 'Yes' THEN 1 ELSE 0 END as Is_Returned,
    r.[Return.Reason]
FROM Orders o
LEFT JOIN Returns r ON o.[Order.ID] = r.[Order.ID]
"""

# 4. Execute the SQL and save the final joined dataset!
final_data = pd.read_sql(sql_query, conn)
final_data.to_csv('Scored_Return_Data_Raw.csv', index=False)

print("✅ Step 2 Complete: SQL JOIN successful!")
print(f"Final dataset has {len(final_data)} rows. Ready for Machine Learning.")
final_data.head()

import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# 1. Load the joined dataset from Step 2
df = pd.read_csv('Scored_Return_Data_Raw.csv')

# 2. Select Features (What causes a return?) and Target (Was it returned?)
# We use Category, Sub-Category, Region, Sales, and Profit to predict.
X = df[['Category', 'Sub.Category', 'Region', 'Sales', 'Profit']]
y = df['Is_Returned']

# 3. Preprocess the Data (Convert Text to Numbers)
# Machine Learning models cannot read text like "Furniture" or "West".
# We use OneHotEncoder to turn these text columns into 1s and 0s.
categorical_features = ['Category', 'Sub.Category', 'Region']
categorical_transformer = OneHotEncoder(handle_unknown='ignore')

# Combine preprocessing steps
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', categorical_transformer, categorical_features)
    ], remainder='passthrough') # 'passthrough' keeps numeric columns (Sales, Profit) as they are

# 4. Build the Machine Learning Pipeline
# We use Logistic Regression and balance the weights (since returns are rare compared to kept items)
clf = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42))
])

# 5. Train the Model!
print("Training the Logistic Regression model... Please wait.")
clf.fit(X, y)

# 6. Predict the Return Probabilities for all orders
# 'predict_proba' gives us the probability. We extract the probability of "1" (Being Returned).
probabilities = clf.predict_proba(X)[:, 1]

# Add this new score as a column in our dataset
df['Return_Probability_%'] = np.round(probabilities * 100, 2)

# 7. Save the final Scored Dataset (For Power BI!)
df.to_csv('Scored_Return_Data.csv', index=False)

# 8. Create a separate file for High-Risk items (e.g., probability > 70%)
high_risk = df[df['Return_Probability_%'] > 70].sort_values(by='Return_Probability_%', ascending=False)
high_risk.to_csv('High_Risk_Products.csv', index=False)

print("✅ Step 3 Complete: Machine Learning Scoring Finished!")
print(f"Exported 'Scored_Return_Data.csv' with {len(df)} scored orders.")
print(f"Identified {len(high_risk)} high-risk items and saved to 'High_Risk_Products.csv'.")

# Preview the High-Risk items
high_risk[['Product.Name', 'Category', 'Sales', 'Return_Probability_%']].head()